services:
  db:
    image: postgres:16
    container_name: social-postgres
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: social
      POSTGRES_PASSWORD: socialpwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 12

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: socialapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/socialdb
      SPRING_DATASOURCE_USERNAME: social
      SPRING_DATASOURCE_PASSWORD: socialpwd
    ports:
      - "8080:8080"

volumes:
  pgdata:
